# Generated by Django 5.2.5 on 2025-09-22 14:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0003_refundrequest'),
    ]

    operations = [
        migrations.AddField(
            model_name='refundrequest',
            name='amount',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True),
        ),
    ]
