# Generated by Django 5.2.5 on 2025-09-22 14:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0005_booking_cancellation_reason_and_more'),
        ('payments', '0004_refundrequest_amount'),
    ]

    operations = [
        migrations.AddField(
            model_name='refundrequest',
            name='booking',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='refund_requests', to='booking.booking'),
        ),
    ]
