# Generated by Django 5.2.5 on 2025-08-14 09:34

import cloudinary.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='voucher',
            field=cloudinary.models.CloudinaryField(blank=True, max_length=255, null=True, verbose_name='voucher'),
        ),
    ]
