# Generated by Django 5.2.5 on 2025-09-05 15:37

import cloudinary.models
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0004_booking_note_booking_package'),
        ('catalog', '0006_tourpackage_organizer_alter_destination_cover_image'),
        ('contenttypes', '0002_remove_content_type_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='cancellation_reason',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='booking',
            name='external_reference',
            field=models.CharField(blank=True, help_text='External provider booking ID', max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='booking',
            name='external_service',
            field=models.CharField(blank=True, help_text='External provider name (Amadeus, Duffel, etc.)', max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='booking',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='bookingitem',
            name='external_data',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='booking',
            name='package',
            field=models.ForeignKey(blank=True, help_text='Optional link to a tour package', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='bookings', to='catalog.tourpackage'),
        ),
        migrations.AlterField(
            model_name='booking',
            name='voucher',
            field=cloudinary.models.CloudinaryField(blank=True, help_text='Optional upload of proof or travel voucher', max_length=255, null=True, verbose_name='voucher'),
        ),
        migrations.AlterField(
            model_name='bookingitem',
            name='content_type',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='contenttypes.contenttype'),
        ),
        migrations.AlterField(
            model_name='bookingitem',
            name='object_id',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
    ]
