# Generated by Django 5.2.5 on 2025-08-26 12:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0002_car_carimage_hotel_cover_image_roomtype_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='roomtype',
            name='availiability',
            field=models.PositiveBigIntegerField(default=1, help_text='Number of currently available rooms of this type'),
        ),
    ]
