# Generated by Django 5.2.5 on 2025-08-28 11:36

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0005_alter_destination_options_and_more'),
        ('inventory', '0003_roomtype_availiability'),
    ]

    operations = [
        migrations.AddField(
            model_name='car',
            name='destination',
            field=models.ForeignKey(default=5, on_delete=django.db.models.deletion.CASCADE, related_name='cars', to='catalog.destination'),
            preserve_default=False,
        ),
    ]
