# Generated by Django 5.2.5 on 2025-09-02 16:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0004_car_destination'),
    ]

    operations = [
        migrations.RenameField(
            model_name='roomtype',
            old_name='availiability',
            new_name='availability',
        ),
    ]
