# Generated by Django 5.2.5 on 2025-09-07 05:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0005_rename_availiability_roomtype_availability'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='hotel',
            name='inventory_h_destina_a8bd15_idx',
        ),
        migrations.AddField(
            model_name='hotel',
            name='city',
            field=models.CharField(default='Unknown', max_length=100),
        ),
        migrations.AddField(
            model_name='hotel',
            name='country',
            field=models.CharField(default='Unknown', max_length=100),
        ),
        migrations.AlterField(
            model_name='hotel',
            name='destination',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddIndex(
            model_name='hotel',
            index=models.Index(fields=['country', 'city', 'is_active'], name='inventory_h_country_4e5dd9_idx'),
        ),
    ]
