# Generated by Django 5.2.5 on 2025-09-07 09:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0007_hotel_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='car',
            name='driver_contact',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='car',
            name='driver_name',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
