# Generated by Django 5.2.5 on 2025-09-08 16:11

import inventory.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0009_flight'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='flight',
            options={},
        ),
        migrations.AddField(
            model_name='flight',
            name='airline',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='flight',
            name='arrival_time',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='flight',
            name='departure_time',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='flight',
            name='expires_at',
            field=models.DateTimeField(default=inventory.models.default_expiry),
        ),
        migrations.AddField(
            model_name='flight',
            name='seats_available',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='flight',
            name='departure_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='flight',
            name='offer_id',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='flight',
            name='provider',
            field=models.CharField(max_length=100),
        ),
    ]
