# Generated by Django 5.2.5 on 2025-09-10 10:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0010_alter_flight_options_flight_airline_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='flight',
            name='flight_number',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
