# Generated by Django 5.2.5 on 2025-08-14 09:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reviews', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='review',
            name='user_avatar_url',
            field=models.URLField(blank=True, help_text="Snapshot of user's avatar at time of review", max_length=500, null=True),
        ),
    ]
