# Generated by Django 5.2.5 on 2025-08-15 09:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0002_destination_cover_image_tourpackage_main_image_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='tourpackage',
            name='end_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='tourpackage',
            name='start_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
