# Generated by Django 5.2.5 on 2025-08-26 18:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0003_tourpackage_end_date_tourpackage_start_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='destination',
            name='slug',
            field=models.SlugField(blank=True, max_length=160, unique=True),
        ),
    ]
