# Generated by Django 5.2.5 on 2025-09-11 10:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0006_tourpackage_organizer_alter_destination_cover_image'),
        ('inventory', '0011_flight_flight_number'),
    ]

    operations = [
        migrations.AddField(
            model_name='tourpackage',
            name='car',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='tour_packages', to='inventory.car'),
        ),
        migrations.AddField(
            model_name='tourpackage',
            name='car_days',
            field=models.PositiveSmallIntegerField(default=1),
        ),
        migrations.AddField(
            model_name='tourpackage',
            name='commission',
            field=models.DecimalField(decimal_places=2, default=0.0, help_text='Organizer commission %', max_digits=5),
        ),
        migrations.AddField(
            model_name='tourpackage',
            name='hotel',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='tour_packages', to='inventory.hotel'),
        ),
        migrations.AddField(
            model_name='tourpackage',
            name='nights',
            field=models.PositiveSmallIntegerField(default=1),
        ),
    ]
