# Generated by Django 5.2.5 on 2025-09-11 16:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0007_tourpackage_car_tourpackage_car_days_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='tourpackage',
            name='highlights',
            field=models.TextField(blank=True, help_text='Key package highlights'),
        ),
        migrations.AddField(
            model_name='tourpackage',
            name='policies',
            field=models.TextField(blank=True, help_text='Important policies'),
        ),
    ]
