# Generated by Django 5.2.5 on 2025-09-26 14:37

import cloudinary.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0008_tourpackage_highlights_tourpackage_policies'),
    ]

    operations = [
        migrations.AlterField(
            model_name='destination',
            name='cover_image',
            field=cloudinary.models.CloudinaryField(blank=True, max_length=255, null=True, verbose_name='image'),
        ),
    ]
